version: "3"

services:
    php73:
        build:
            context: "./build/php-fpm/7.3-alpine"
            dockerfile: "Dockerfile"
        environment: 
            - NEW_GID=$GIANT_USER
            - NEW_UID=$GIANT_GROUP
        sysctls:
        - net.ipv6.conf.all.disable_ipv6=1
        - net.ipv6.conf.default.disable_ipv6=1            